#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xACEB29740C9A4E97 (mattst88@gmail.com)
#
Name     : xcb-proto
Version  : 1.16.0
Release  : 60
URL      : https://www.x.org/releases/individual/proto/xcb-proto-1.16.0.tar.xz
Source0  : https://www.x.org/releases/individual/proto/xcb-proto-1.16.0.tar.xz
Source1  : https://www.x.org/releases/individual/proto/xcb-proto-1.16.0.tar.xz.sig
Summary  : X protocol descriptions for XCB
Group    : Development/Tools
License  : MIT
Requires: xcb-proto-data = %{version}-%{release}
Requires: xcb-proto-license = %{version}-%{release}
Requires: xcb-proto-python = %{version}-%{release}
Requires: xcb-proto-python3 = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxml2-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
About xcb-proto
===============
xcb-proto provides the XML-XCB protocol descriptions that libxcb uses to
generate the majority of its code and API. We provide them separately
from libxcb to allow reuse by other projects, such as additional
language bindings, protocol dissectors, or documentation generators.

%package data
Summary: data components for the xcb-proto package.
Group: Data

%description data
data components for the xcb-proto package.


%package dev
Summary: dev components for the xcb-proto package.
Group: Development
Requires: xcb-proto-data = %{version}-%{release}
Provides: xcb-proto-devel = %{version}-%{release}
Requires: xcb-proto = %{version}-%{release}

%description dev
dev components for the xcb-proto package.


%package dev32
Summary: dev32 components for the xcb-proto package.
Group: Default
Requires: xcb-proto-data = %{version}-%{release}
Requires: xcb-proto-dev = %{version}-%{release}

%description dev32
dev32 components for the xcb-proto package.


%package license
Summary: license components for the xcb-proto package.
Group: Default

%description license
license components for the xcb-proto package.


%package python
Summary: python components for the xcb-proto package.
Group: Default
Requires: xcb-proto-python3 = %{version}-%{release}

%description python
python components for the xcb-proto package.


%package python3
Summary: python3 components for the xcb-proto package.
Group: Default
Requires: python3-core

%description python3
python3 components for the xcb-proto package.


%prep
%setup -q -n xcb-proto-1.16.0
cd %{_builddir}/xcb-proto-1.16.0
pushd ..
cp -a xcb-proto-1.16.0 build32
popd
pushd ..
cp -a xcb-proto-1.16.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692227510
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../build32;
make %{?_smp_mflags} check || : || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1692227510
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xcb-proto
cp %{_builddir}/xcb-proto-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xcb-proto/1d6467e08284270291d138c7ea07f24689483068 || :
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/xcb/bigreq.xml
/usr/share/xcb/composite.xml
/usr/share/xcb/damage.xml
/usr/share/xcb/dbe.xml
/usr/share/xcb/dpms.xml
/usr/share/xcb/dri2.xml
/usr/share/xcb/dri3.xml
/usr/share/xcb/ge.xml
/usr/share/xcb/glx.xml
/usr/share/xcb/present.xml
/usr/share/xcb/randr.xml
/usr/share/xcb/record.xml
/usr/share/xcb/render.xml
/usr/share/xcb/res.xml
/usr/share/xcb/screensaver.xml
/usr/share/xcb/shape.xml
/usr/share/xcb/shm.xml
/usr/share/xcb/sync.xml
/usr/share/xcb/xc_misc.xml
/usr/share/xcb/xcb.xsd
/usr/share/xcb/xevie.xml
/usr/share/xcb/xf86dri.xml
/usr/share/xcb/xf86vidmode.xml
/usr/share/xcb/xfixes.xml
/usr/share/xcb/xinerama.xml
/usr/share/xcb/xinput.xml
/usr/share/xcb/xkb.xml
/usr/share/xcb/xprint.xml
/usr/share/xcb/xproto.xml
/usr/share/xcb/xselinux.xml
/usr/share/xcb/xtest.xml
/usr/share/xcb/xv.xml
/usr/share/xcb/xvmc.xml

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/xcb-proto.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32xcb-proto.pc
/usr/lib32/pkgconfig/xcb-proto.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xcb-proto/1d6467e08284270291d138c7ea07f24689483068

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
